s=input('digite algo: ')
print('o tipo primitivo da variável é ',type(s))
print('só tem espaço? ',s.isspace())
print('é alpha numerico? ',s.isalnum())
print('é só alfabetico? ',s.isalpha())
print('é só numero? ',s.isnumeric())
print('é decimal? ',s.isdecimal())
print('é letra maiuscula? ',s.isupper())
print('é letra minuscula? ',s.istitle())