print('-'*100)
print('software de desconto em compras \n')
print('-'*100)

produto=input('digite o nome do produto: ')
quantidade=int(input('digite a quantidade comprada: '))
valor=float(input('digite o valor unitário de cada produto: '))
valor_compra=float(quantidade*valor)
print('O valor da total da compra é: %.2f Reais'%(valor_compra))
desconto=int(input('digite a porcentagem de desconto: '))
print('porcentagem de desconto é: %d'%(desconto))
valor_final=float(valor_compra-(valor_compra*desconto/100))
print('valor com desconto é: %.2f'%(valor_final))
print('-'*100)
print('vc comprou %d %s e o valor para pagamento é: %.2f'%(quantidade,produto,valor_final))
print('-'*100)
