produto=input("digite o nome do produto ")
valor_unitario=float(input("digite o valor unitario: "))
quantidade=int(input("digite a quantidade comprada: "))
desconto=float(input("digite o valor do desconto em porcentagem: "))
valor_final=float(quantidade*valor_unitario)
valor_desconto=(valor_final-(valor_final*desconto/100))
print(50*"-")
print(produto)
print("total da compra = ",valor_desconto)