print('cadastro de aluno')
print('='*120)
nome=input('Digite o nome do aluno: ')
serie=input('Digite a serie do aluno: ')
escola=input('Digite a escola do aluno: ')
cidade=input('Digite a cidade do aluno: ')
print('='*120)
n1=float(input('Digite a 1 nota bimestral: '))
n2=float(input('Digite a 2 nota bimestral: '))
n3=float(input('Digite a 3 nota bimestral: '))
n4=float(input('Digite a 4 nota bimestral: '))
media=float((n1+n2+n3+n4)/4)
print('='*120)
print('Media final = {}'.format(media))
print('='*120)
print('O aluno {} da escola {} que cursa a {} serie da cidade {} foi com media final de {}'.format(nome,escola,serie,cidade,media))
print('='*120)
